### ISSUE TITLE
fix all fixme

### ISSUE THREAD

**Issue by jojoc4** [HE-Arc/Perroquet#47]
- [x] Settings.vue mail depends on #43 
- [x] Settings.vue password depends on #44 
- [x] index.js removeLike depends on #36
- [x] index.js unfollow depends on #41 
- [x] index.js add filter in getProfileMessage depends on #35
